<a href="https://colab.research.google.com/github/harshchaturkar/Mini-Project-repo/blob/main/20_Optional_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv("./ford_car.csv")
df

,model,year,price,transmission,mileage,fuelType,tax,mpg,engineSize
0,Fiesta,2017,12000,Automatic,15944,Petrol,150,57.7,1.0
1,Focus,2018,14000,Manual,9083,Petrol,150,57.7,1.0
2,Focus,2017,13000,Manual,12456,Petrol,150,57.7,1.0
3,Fiesta,2019,17500,Manual,10460,Petrol,145,40.3,1.5
4,Fiesta,2019,16500,Automatic,1482,Petrol,145,48.7,1.0
...,...,...,...,...,...,...,...,...,...
17961,B-MAX,2017,8999,Manual,16700,Petrol,150,47.1,1.4
17962,B-MAX,2014,7499,Manual,40700,Petrol,30,57.7,1.0
17963,Focus,2015,9999,Manual,7010,Diesel,20,67.3,1.6
17964,KA,2018,8299,Manual,5007,Petrol,145,57.7,1.2
17965,Focus,2015,8299,Manual,5007,Petrol,22,57.7,1.0

In [ ]:
df.describe()

,year,price,mileage,tax,mpg,engineSize
count,17966.000000,17966.000000,17966.000000,17966.000000,17966.000000,17966.000000
mean,2016.866470,12279.534844,23362.608761,113.329456,57.906980,1.350807
std,2.050336,4741.343657,19472.054349,62.012456,10.125696,0.432367
min,1996.000000,495.000000,1.000000,0.000000,20.800000,0.000000
25%,2016.000000,8999.000000,9987.000000,30.000000,52.300000,1.000000
50%,2017.000000,11291.000000,18242.500000,145.000000,58.900000,1.200000
75%,2018.000000,15299.000000,31060.000000,145.000000,65.700000,1.500000
max,2060.000000,54995.000000,177644.000000,580.000000,201.800000,5.000000

In [ ]:
df.dtypes

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [ ]:
x = df.drop('price',axis=1)
y = df['price']
print(" Independent Features (X) :")
print(x.columns)
print("\nDependent Feature (Y) :")
print(y.name)
print("\nShape of x :")
print(x.shape)
print("Shape of y :")
print(y.shape)

 Independent Features (X) :
Index(['model', 'year', 'transmission', 'mileage', 'fuelType', 'tax', 'mpg',
       'engineSize'],
      dtype='object')

Dependent Feature (Y) :
price

Shape of x :
(17966, 8)
Shape of y :
(17966,)

In [ ]:
cat_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns :")
print(cat_cols)

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
print("\nNumerical columns :")
print(num_cols)
num_cols = num_cols.drop('price')

Categorical columns :
Index(['model', 'transmission', 'fuelType'], dtype='object')

Numerical columns :
Index(['year', 'price', 'mileage', 'tax', 'mpg', 'engineSize'], dtype='object')

In [ ]:
encoded = pd.get_dummies(df[cat_cols])
convert = encoded.astype(int)
convert.head()

,model_ B-MAX,model_ C-MAX,model_ EcoSport,model_ Edge,model_ Escort,model_ Fiesta,model_ Focus,model_ Fusion,model_ Galaxy,model_ Grand C-MAX,...,model_ Transit Tourneo,model_Focus,transmission_Automatic,transmission_Manual,transmission_Semi-Auto,fuelType_Diesel,fuelType_Electric,fuelType_Hybrid,fuelType_Other,fuelType_Petrol
0,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
4,0,0,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df[num_cols])
scaled_df = pd.DataFrame(scaled_features, columns=num_cols)
scaled_df

           year   mileage       tax       mpg  engineSize
0      0.065128 -0.380998  0.591358 -0.020442   -0.811386
1      0.552866 -0.733359  0.591358 -0.020442   -0.811386
2      0.065128 -0.560132  0.591358 -0.020442   -0.811386
3      1.040605 -0.662640  0.510727 -1.738890    0.345070
4      1.040605 -1.123724  0.510727 -0.909294   -0.811386
...         ...       ...       ...       ...         ...
17961  0.065128 -0.342172  0.591358 -1.067312    0.113779
17962 -1.398088  0.890398 -1.343791 -0.020442   -0.811386
17963 -0.910349 -0.839822 -1.505053  0.927668    0.576362
17964  0.552866 -0.942690  0.510727 -0.020442   -0.348804
17965 -0.910349 -0.942690 -1.472801 -0.020442   -0.811386

[17966 rows x 5 columns]

In [ ]:
convert = pd.concat([scaled_df,convert],axis=1)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.model_selection import train_test_split

x = convert
y = df['price']
x = x.fillna(x.mean()) # Impute NaN values with the mean of each column

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)
model = LinearRegression()
model.fit(X_train, y_train)
# Ya block cha screen shot pathavshil

LinearRegression()

In [ ]:
y_pred = model.predict(X_test)

print(y_pred[:10])

print(y_test.iloc[:10])

[ 6676.74792864  9175.10363172  9876.15109278  3808.41679254
  2944.77931074 16623.10788236 27571.14532174 12128.40953688
 11577.4693611  16774.32274028]
17610     6995
7076      8999
1713      7998
1611      5491
16830     3790
14735    18200
322      22998
8164     11000
6822      7600
2133     14985
Name: price, dtype: int64

In [ ]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.8408137113174078

In [ ]:
import joblib

# Save the trained Linear Regression model
joblib.dump(model, "ford_car.pkl")

# Save the StandardScaler object
joblib.dump(scaler, "scaler.pkl")

# Save the list of feature columns
joblib.dump(convert.columns.tolist(), "columns.pkl")

print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!