In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("./heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [ ]:
x = df.drop("HeartDisease", axis=1)
y = df["HeartDisease"]
print("Independent features :")
print(x)
print("\nDependent features :")
print(y)

Independent features :
     Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal
1     49   F           NAP        160          180          0     Normal
2     37   M           ATA        130          283          0         ST
3     48   F           ASY        138          214          0     Normal
4     54   M           NAP        150          195          0     Normal
..   ...  ..           ...        ...          ...        ...        ...
913   45   M            TA        110          264          0     Normal
914   68   M           ASY        144          193          1     Normal
915   57   M           ASY        130          131          0     Normal
916   57   F           ATA        130          236          0        LVH
917   38   M           NAP        138          175          0     Normal

     MaxHR ExerciseAngina  Oldpeak ST_Slope
0      172              N      0.0       Up
1      156              N      1.0     Flat
2       98              N      0.0       Up
3      108              Y      1.5     Flat
4      122              N      0.0       Up
..     ...            ...      ...      ...
913    132              N      1.2     Flat
914    141              N      3.4     Flat
915    115              Y      1.2     Flat
916    174              N      0.0     Flat
917    173              N      0.0       Up

[918 rows x 11 columns]

Dependent features :
0      0
1      1
2      0
3      1
4      0
      ..
913    1
914    1
915    1
916    1
917    0
Name: HeartDisease, Length: 918, dtype: int64

In [ ]:
encoded = pd.get_dummies(x)
encoded = encoded.astype(int)
encoded

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0,0,1,0,1,0,0,0,1,0,1,0,0,0,1
1,49,160,180,0,156,1,1,0,0,0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0,0,1,0,1,0,0,0,0,1,1,0,0,0,1
3,48,138,214,0,108,1,1,0,1,0,0,0,0,1,0,0,1,0,1,0
4,54,150,195,0,122,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1,0,1,0,0,0,1,0,1,0,1,0,0,1,0
914,68,144,193,1,141,3,0,1,1,0,0,0,0,1,0,1,0,0,1,0
915,57,130,131,0,115,1,0,1,1,0,0,0,0,1,0,0,1,0,1,0
916,57,130,236,0,174,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0
917,38,138,175,0,173,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(encoded, y, test_size=0.20,  random_state=42)

print("Shape of X_train :", X_train.shape)
print("Shape of X_test :", X_test.shape)
print("Shape of y_train :", X_train.shape)
print("Shape of y_test :", X_test.shape)

Shape of X_train : (734, 20)
Shape of X_test : (184, 20)
Shape of y_train : (734, 20)
Shape of y_test : (184, 20)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
print("First 10 actual values :")
print(y_test.head(10))
print("\nFirst 10 predicted values :")
print(y_pred[:10])

First 10 actual values :
668    0
30     1
377    1
535    1
807    0
793    1
363    1
583    0
165    1
483    1
Name: HeartDisease, dtype: int64

First 10 predicted values :
[0 0 1 1 0 1 1 0 1 1]

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_pred, y_test)
print(cm)

print("\nTrue Negative :",cm[0][0])
print("\nFalse Positive :",cm[0][1])
print("\nFalse Negative :",cm[1][0])
print("\nTrue Positive :",cm[1][1])

[[67 17]
 [10 90]]

True Negative : 67

False Positive : 17

False Negative : 10

True Positive : 90

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

print("Accuracy :", accuracy_score(y_pred, y_test))
print("\nPrecision :", precision_score(y_pred, y_test))
print("\nRecall :", recall_score(y_pred, y_test))
print("\nF1 score :", f1_score(y_pred, y_test))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy : 0.8532608695652174

Precision : 0.8411214953271028

Recall : 0.9

F1 score : 0.8695652173913043

Classification Report:
              precision    recall  f1-score   support

           0       0.80      0.87      0.83        77
           1       0.90      0.84      0.87       107

    accuracy                           0.85       184
   macro avg       0.85      0.86      0.85       184
weighted avg       0.86      0.85      0.85       184

In [ ]:
import joblib

joblib.dump(model, "heart.pkl")
joblib.dump(encoded.columns.tolist(), "columns.pkl")

print("Model and columns saved successfully!")

Model and columns saved successfully!

In [ ]:
import joblib
import pandas as pd
model = joblib.load("heart.pkl")
columns = joblib.load("columns.pkl")

sample = pd.DataFrame({
    "Age": [40],
    "sex": [1],
    "ChestPainType": [1],
    "RestingBP": [140],
    "Cholesterol": [289],
    "FastingBS": [0],
    "RestingECG": [1],
    "MaxHR": [172],
    "ExerciseAngina": [1],
    "Oldpeak": [0.0],
    "ST_Slope": [1],
    "HeartDisease": [0]
})

sample = sample.reindex(columns=columns, fill_value=0)

prediction = model.predict(sample)

if prediction[0] == 1:
    print("Prediction: Heart Disease Detected")
else:
    print("Prediction: No Heart Disease")

Prediction: No Heart Disease