<a href="https://colab.research.google.com/github/harshchaturkar/Mini-Project-repo/blob/main/assignment_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('./car_price_dataset.csv')
df

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70
4,5,Hyundai,2012,2.4,Electric,Manual,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Hyundai,2023,4.5,Diesel,Manual,155033,2,3,310,61734.35
1996,1997,Toyota,2023,1.4,Petrol,Manual,25044,2,4,271,48467.80
1997,1998,Hyundai,2022,4.1,Diesel,Manual,104372,4,3,191,55714.40
1998,1999,BMW,2020,4.4,Diesel,Automatic,158047,4,1,186,53222.65
1999,2000,Honda,2012,1.7,Electric,Automatic,19706,3,1,165,40687.70

In [ ]:
x = df.drop('Price',axis=1)
y = df['Price']

print(" Independent Features (X) :")
print(x.columns)
print("\nDependent Feature (Y) :")
print(y.name)
print("\nShape of x :")
print(x.shape)
print("Shape of y :")
print(y.shape)

 Independent Features (X) :
Index(['Car_ID', 'Brand', 'Model_Year', 'Engine_Size', 'Fuel_Type',
       'Transmission', 'Mileage', 'Doors', 'Owner_Count', 'Horsepower'],
      dtype='object')

Dependent Feature (Y) :
Price

Shape of x :
(2000, 10)
Shape of y :
(2000,)

In [ ]:
cat_cols = df.select_dtypes('int64','float64').columns
print(" categorical columns ")
cat_cols

 categorical columns

Index(['Car_ID', 'Model_Year', 'Mileage', 'Doors', 'Owner_Count',
       'Horsepower'],
      dtype='object')

In [ ]:
encoded = pd.get_dummies(df[cat_cols])
encoded
convert =encoded.astype(int)
convert
convert.head()

   Car_ID  Model_Year  Mileage  Doors  Owner_Count  Horsepower
0       1        2023   180635      4            3          82
1       2        2018    35628      2            4         259
2       3        2008    74672      3            2         333
3       4        2017    51246      4            4         381
4       5        2012   147233      3            4         290

In [ ]:
from sklearn.preprocessing import StandardScaler

numeric_cols = ['Model_Year', 'Mileage', 'Doors', 'Owner_Count', 'Horsepower']

scaler = StandardScaler()

scaled_features = scaler.fit_transform(df[numeric_cols])

scaled_df = pd.DataFrame(scaled_features, columns=numeric_cols)

print(scaled_df.head())

   Model_Year   Mileage     Doors  Owner_Count  Horsepower
0    1.641041  1.427033  1.237412     0.415503   -1.608274
1    0.733084 -1.162890 -1.208066     1.304280    0.243690
2   -1.082829 -0.465538  0.014673    -0.473274    1.017958
3    0.551493 -0.883942  1.237412     1.304280    1.520185
4   -0.356464  0.830451  0.014673     1.304280    0.568046

In [ ]:
from sklearn.model_selection import train_test_split

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size=0.33, random_state=42
)

# Print shapes
print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

X_train shape: (1340, 10)
X_test shape : (660, 10)
y_train shape: (1340,)
y_test shape : (660,)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

X_train, X_test, y_train, y_test = train_test_split(convert, y, test_size=0.33, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)
# Print intercept
print("Intercept:", model.intercept_)

# Print coefficients
print("\nCoefficients:", model.coef_)

Intercept: -1598668.4235001483

Coefficients: [-2.36341416e-02  8.14659133e+02 -4.91329800e-02 -1.17940764e+02
 -1.01662019e+03  5.06230406e+01]

In [ ]:
y_pred = model.predict(X_test)

print("First 10 Predicted Values:")
print(y_pred[:10])

print("\nFirst 10 Actual Values:")
print(y_test.iloc[:10])

comparison = pd.DataFrame({
    "Actual": y_test.iloc[:10].values,
    "Predicted": y_pred[:10]
})

print("\nComparison of Actual vs Predicted:")
print(comparison)

First 10 Predicted Values:
[35625.445871   39941.47065334 47531.01580061 43009.78388574
 55270.06664589 53681.99105062 44901.41498776 56528.09078748
 36167.25167749 52991.29463292]

First 10 Actual Values:
1860    43212.35
353     46083.40
1333    52442.80
905     52911.10
1289    56364.50
1273    48364.90
938     49984.80
1731    61124.75
65      35864.65
1323    53218.25
Name: Price, dtype: float64

Comparison of Actual vs Predicted:
     Actual     Predicted
0  43212.35  35625.445871
1  46083.40  39941.470653
2  52442.80  47531.015801
3  52911.10  43009.783886
4  56364.50  55270.066646
5  48364.90  53681.991051
6  49984.80  44901.414988
7  61124.75  56528.090787
8  35864.65  36167.251677
9  53218.25  52991.294633

In [ ]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)

print("R² Score:", r2)

R² Score: 0.5673809195231141

In [ ]:
#The model explains 56.74% of the variation in car prices.
#The model performance is moderate (average).
#The predictions are reasonably accurate, but there is room for improvement.

In [ ]:
import joblib

# Save the trained Linear Regression model
joblib.dump(model, "LR_ford_car.pkl")

# Save the StandardScaler object
joblib.dump(scaler, "scaler.pkl")

# Save the list of feature columns
joblib.dump(convert.columns.tolist(), "columns.pkl")

print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!