<a href="https://colab.research.google.com/github/harshchaturkar/Mini-Project-repo/blob/main/Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Movies.csv to Movies.csv

In [ ]:
filepath = "/content/Movies.csv"
df = pd.read_csv(filepath)

In [ ]:
df

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000

In [ ]:
df.head()

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
0,Golden Boys,Normal,No,No,suspense,Yes,No,No,Jeet Goswami,Ravi Varma,Baba Jagirdar,5,5000000,85000
1,Kaccha Limboo,Holiday,No,No,drama,Yes,No,Yes,Karan Bhanushali,Sagar Ballary,Amardeep Nijjer,75,15000000,825000
2,Not A Love Story,Holiday,No,No,thriller,No,No,No,Mahie Gill,Ram Gopal Verma,Sandeep Chowta,525,75000000,56700000
3,Qaidi Band,Holiday,No,No,drama,Yes,No,No,Aadar Jain,Habib Faisal,Amit Trivedi,800,210000000,4500000
4,Chaatwali,Holiday,No,No,adult,Yes,Yes,Yes,Aadil Khan,Aadil Khan,Babloo Ustad,1,1000000,1075000

In [ ]:
df.tail()

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
1693,Fight Club,Holiday,No,No,action,No,Yes,No,Zayed Khan,Vikram Chopra,Pritam,375,82500000,88862500
1694,Strings Of Paasion,Normal,No,No,drama,No,Yes,Yes,Zeenat Aman,Sanghamitra Chaudhuri,Dev Sikdar,10,8000000,70000
1695,Dunno Y Na Jaane Kyun,Normal,No,No,drama,No,No,No,Zeenat Aman,Sanjay Sharma,Nikhil,20,12500000,850000
1696,Taj Mahal - An Eternal Love Story,Normal,No,No,drama,No,Yes,No,Zulfi Sayed,Akbar Khan,Naushad,135,100000000,31065000
1697,Mr. Hot Mr. Kool,Normal,No,No,comedy,No,No,Yes,Zulfi Sayed,Partho Ghosh,Rishi - Ranjit,30,27500000,1300000

In [ ]:
df.shape

(1698, 14)

In [ ]:
df.columns

Index(['Movie_Name', 'Release_Period', 'Whether_Remake', 'Whether_Franchise',
       'Genre', 'New_Actor', 'New_Director', 'New_Music_Director', 'Lead_Star',
       'Director', 'Music_Director', 'Number_of_Screens', 'Revenue(INR)',
       'Budget(INR)'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1698 entries, 0 to 1697
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Name          1698 non-null   object
 1   Release_Period      1698 non-null   object
 2   Whether_Remake      1698 non-null   object
 3   Whether_Franchise   1698 non-null   object
 4   Genre               1698 non-null   object
 5   New_Actor           1698 non-null   object
 6   New_Director        1698 non-null   object
 7   New_Music_Director  1698 non-null   object
 8   Lead_Star           1698 non-null   object
 9   Director            1698 non-null   object
 10  Music_Director      1698 non-null   object
 11  Number_of_Screens   1698 non-null   int64
 12  Revenue(INR)        1698 non-null   int64
 13  Budget(INR)         1698 non-null   int64
dtypes: int64(3), object(11)
memory usage: 185.8+ KB

In [ ]:
df.describe()

       Number_of_Screens  Revenue(INR)   Budget(INR)
count        1698.000000  1.698000e+03  1.698000e+03
mean          553.831567  1.501674e+08  2.377287e+08
std           782.951839  2.434838e+08  6.134398e+08
min             1.000000  3.250000e+05  7.250000e+03
25%            30.000000  1.500000e+07  1.150000e+06
50%           200.000000  5.500000e+07  1.240000e+07
75%           800.000000  1.900000e+08  1.778325e+08
max          4600.000000  2.100000e+09  8.016120e+09

In [ ]:
df.dtypes

Movie_Name            object
Release_Period        object
Whether_Remake        object
Whether_Franchise     object
Genre                 object
New_Actor             object
New_Director          object
New_Music_Director    object
Lead_Star             object
Director              object
Music_Director        object
Number_of_Screens      int64
Revenue(INR)           int64
Budget(INR)            int64
dtype: object

In [ ]:
df.isnull().sum()

Movie_Name            0
Release_Period        0
Whether_Remake        0
Whether_Franchise     0
Genre                 0
New_Actor             0
New_Director          0
New_Music_Director    0
Lead_Star             0
Director              0
Music_Director        0
Number_of_Screens     0
Revenue(INR)          0
Budget(INR)           0
dtype: int64

In [ ]:
df.nunique()

Movie_Name            1695
Release_Period           2
Whether_Remake           2
Whether_Franchise        2
Genre                   14
New_Actor                2
New_Director             2
New_Music_Director       2
Lead_Star              764
Director              1048
Music_Director         630
Number_of_Screens      147
Revenue(INR)           184
Budget(INR)           1104
dtype: int64

In [ ]:
df.sample(10)

,Movie_Name,Release_Period,Whether_Remake,Whether_Franchise,Genre,New_Actor,New_Director,New_Music_Director,Lead_Star,Director,Music_Director,Number_of_Screens,Revenue(INR),Budget(INR)
217,Kaam Milan,Holiday,No,No,adult,No,No,Yes,Amit Pachori,Chandini Gupta,Avi Raaj,1,1500000,825000
1688,Hate Story 3,Normal,No,Yes,thriller,No,No,Yes,Zarine Khan,Vishal Pandya,Baman,2600,200000000,622125000
163,De Dana Dan,Holiday,No,No,comedy,No,No,No,Akshay Kumar,Priyadarshan,Pritam,1550,600000000,818520000
699,Pyaar Ka Punchnama,Normal,No,No,rom__com,Yes,Yes,Yes,Kartik Aryan,Luv Ranjan,Clinton Cerejo,550,97500000,170300000
381,MLA,Normal,No,No,drama,Yes,Yes,No,Chaitanya Naidu,Shiv Dube,Sandesh Shandilya,55,17500000,675000
922,Chala Mussaddi - Office Office,Normal,No,No,comedy,No,No,No,Pankaj Kapoor,Rajiv Mehra,Sajid - Wajid,350,65000000,13900000
1333,2 Piece,Normal,No,No,adult,No,No,No,Satnam Kaur,Kishan Shah,Sawan Kumar Sawan,2,1500000,1500000
1485,Padmashree Laloo Prasad Yadav,Normal,No,No,comedy,No,No,No,Suneil Shetty,Mahesh Manjrekar,Nitin Raikwar,150,65000000,24283000
805,Hum Tum Aur Mom,Normal,No,No,drama,Yes,Yes,Yes,Mehrunnisa Hassan,Ashok Nanda,K.P.,5,20000000,400000
1511,Khichdi The Movie,Holiday,Yes,No,comedy,No,Yes,No,Supriya Pathak,Aatish Kapadia,Raju Singh,400,45000000,81700000

In [ ]:
df.value_counts()

Movie_Name           Release_Period  Whether_Remake  Whether_Franchise  Genre     New_Actor  New_Director  New_Music_Director  Lead_Star          Director             Music_Director          Number_of_Screens  Revenue(INR)  Budget(INR)
Game                 Holiday         Yes             No                 thriller  No         Yes           No                  Abhishek Bachchan  Abhinay Deo          Shankar - Ehsaan - Loy  1100               340000000     128792500      2
Aatma                Normal          No              No                 horror    No         No            No                  Bipasha Basu       Deepak Ramsay        Anu Malik               70                 25000000      9400000        2
Nishabd              Holiday         No              No                 drama     No         No            No                  Amitabh Bachchan   Ram Gopal Verma      Vishal Bhardwaj         400                85000000      117120000      1
Nil Battey Sannatta  Normal          No              No                 drama     No         Yes           Yes                 Swara Bhaskar      Ashwiny Iyer Tiwari  Rohan - Vinayak         300                75000000      58300000       1
Night Lover          Normal          No              No                 adult     No         No            Yes                 Tanveer Hashmi     Suresh Jain          Shivam Bagchi           1                  1250000       400000         1
                                                                                                                                                                                                                                              ..
Good Boy Bad Boy     Normal          No              No                 comedy    No         No            No                  Emraan Hashmi      Ashwini Chaudhary    Himesh Reshammiya       525                125000000     103268750      1
Golmaal Returns      Holiday         No              Yes                comedy    No         No            Yes                 Ajay Devgn         Rohit Shetty         Ashish Pandit           1250               350000000     800080000      1
Golmaal Again        Holiday         No              Yes                comedy    No         No            Yes                 Ajay Devgn         Rohit Shetty         DJ Chetas               3300               1420000000    3110450000     1
Golmaal 3            Holiday         No              Yes                comedy    No         No            No                  Ajay Devgn         Rohit Shetty         Pritam                  1750               500000000     1695635000     1
Gulaab Gang          Normal          No              No                 drama     No         Yes           Yes                 Madhuri Dixit      Soumik Sen           Soumik Sen              1700               290000000     165890000      1
Name: count, Length: 1696, dtype: int64