In [ ]:
import numpy as np
import pandas as pd
import joblib

In [ ]:
df = pd.read_csv("./student_performance_dataset.csv")
df

,student_id,gender,study_time_hours,attendance_percent,sleep_hours,parental_education,internet_access,extracurricular_activities,part_time_job,previous_grade,final_exam_score,final_grade
0,1,Male,4.0,98.0,6.5,Bachelors,Yes,Yes,No,76.9,100.0,A
1,2,Female,6.3,100.0,5.7,High School,Yes,Yes,Yes,75.5,100.0,A
2,3,Male,4.9,85.3,7.9,Bachelors,Yes,No,Yes,88.5,97.3,A
3,4,Male,2.6,77.5,8.0,NaN,Yes,Yes,No,85.1,83.8,B
4,5,Male,2.2,89.6,4.6,Bachelors,Yes,No,Yes,61.8,68.3,D
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Male,2.8,75.4,8.2,Masters,Yes,Yes,No,60.5,70.7,C
996,997,Male,6.7,88.4,7.1,NaN,No,Yes,No,82.2,99.5,A
997,998,Female,2.6,84.5,8.0,High School,Yes,Yes,Yes,65.2,79.2,C
998,999,Female,4.6,85.3,8.1,High School,No,No,Yes,52.2,82.2,B
999,1000,Male,3.9,77.4,6.1,Masters,Yes,No,No,45.4,70.4,C

In [ ]:
df.describe()

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,3.570700,85.092300,6.799500,69.740900,83.543500
std,288.819436,1.478559,9.270685,1.203527,12.613425,10.341333
min,1.000000,0.500000,54.800000,3.200000,31.300000,46.800000
25%,250.750000,2.600000,78.800000,5.900000,61.000000,76.075000
50%,500.500000,3.600000,85.200000,6.800000,69.600000,83.800000
75%,750.250000,4.500000,91.900000,7.600000,78.400000,91.525000
max,1000.000000,8.100000,100.000000,10.000000,100.000000,100.000000

In [ ]:
x = df.drop(["final_grade","final_exam_score"], axis=1)
y = df["final_grade"]
print("Independent features :")
print(x)
print("Dependent features :")
print(y)

Independent features :
     student_id  gender  study_time_hours  attendance_percent  sleep_hours  \
0             1    Male               4.0                98.0          6.5
1             2  Female               6.3               100.0          5.7
2             3    Male               4.9                85.3          7.9
3             4    Male               2.6                77.5          8.0
4             5    Male               2.2                89.6          4.6
..          ...     ...               ...                 ...          ...
995         996    Male               2.8                75.4          8.2
996         997    Male               6.7                88.4          7.1
997         998  Female               2.6                84.5          8.0
998         999  Female               4.6                85.3          8.1
999        1000    Male               3.9                77.4          6.1

    parental_education internet_access extracurricular_activities  \
0            Bachelors             Yes                        Yes
1          High School             Yes                        Yes
2            Bachelors             Yes                         No
3                  NaN             Yes                        Yes
4            Bachelors             Yes                         No
..                 ...             ...                        ...
995            Masters             Yes                        Yes
996                NaN              No                        Yes
997        High School             Yes                        Yes
998        High School              No                         No
999            Masters             Yes                         No

    part_time_job  previous_grade
0              No            76.9
1             Yes            75.5
2             Yes            88.5
3              No            85.1
4             Yes            61.8
..            ...             ...
995            No            60.5
996            No            82.2
997           Yes            65.2
998           Yes            52.2
999            No            45.4

[1000 rows x 10 columns]
Dependent features :
0      A
1      A
2      A
3      B
4      D
      ..
995    C
996    A
997    C
998    B
999    C
Name: final_grade, Length: 1000, dtype: object

In [ ]:
cat_cols = df.select_dtypes(include=["object"]).columns
num_cols = df.select_dtypes(include=["int64","float64"]).columns
print("Categorical colums")
print(cat_cols)
print("Numerical columns")
print(num_cols)
#cat_cols = df.drop("final_grade",axis=1)
#num_cols = df.drop("student_id",axis=1)

Categorical colums
Index(['gender', 'parental_education', 'internet_access',
       'extracurricular_activities', 'part_time_job', 'final_grade'],
      dtype='object')
Numerical columns
Index(['student_id', 'study_time_hours', 'attendance_percent', 'sleep_hours',
       'previous_grade', 'final_exam_score'],
      dtype='object')

In [ ]:
encoded = pd.get_dummies(df[cat_cols])
encoded = encoded.astype(int)
encoded

,gender_Female,gender_Male,parental_education_Bachelors,parental_education_High School,parental_education_Masters,parental_education_PhD,internet_access_No,internet_access_Yes,extracurricular_activities_No,extracurricular_activities_Yes,part_time_job_No,part_time_job_Yes,final_grade_A,final_grade_B,final_grade_C,final_grade_D,final_grade_F
0,0,1,1,0,0,0,0,1,0,1,1,0,1,0,0,0,0
1,1,0,0,1,0,0,0,1,0,1,0,1,1,0,0,0,0
2,0,1,1,0,0,0,0,1,1,0,0,1,1,0,0,0,0
3,0,1,0,0,0,0,0,1,0,1,1,0,0,1,0,0,0
4,0,1,1,0,0,0,0,1,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,1,0,0,1,0,0,1,0,1,1,0,0,0,1,0,0
996,0,1,0,0,0,0,1,0,0,1,1,0,1,0,0,0,0
997,1,0,0,1,0,0,0,1,0,1,0,1,0,0,1,0,0
998,1,0,0,1,0,0,1,0,1,0,0,1,0,1,0,0,0
999,0,1,0,0,1,0,0,1,1,0,1,0,0,0,1,0,0

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled = scaler.fit_transform(df[num_cols])
scaled = pd.DataFrame(scaled,columns=num_cols)
scaled

,student_id,study_time_hours,attendance_percent,sleep_hours,previous_grade,final_exam_score
0,-1.730320,0.290495,1.393010,-0.248976,0.567862,1.592129
1,-1.726856,1.846842,1.608852,-0.914022,0.456813,1.592129
2,-1.723391,0.899501,0.022415,0.914853,1.487977,1.330910
3,-1.719927,-0.656846,-0.819368,0.997984,1.218288,0.024816
4,-1.716463,-0.927515,0.486475,-1.828459,-0.629874,-1.474774
...,...,...,...,...,...,...
995,1.716463,-0.521511,-1.046001,1.164245,-0.732991,-1.242579
996,1.719927,2.117511,0.356970,0.249808,0.988259,1.543755
997,1.723391,-0.656846,-0.063922,0.997984,-0.360185,-0.420224
998,1.726856,0.696499,0.022415,1.081114,-1.391349,-0.129981
999,1.730320,0.222828,-0.830160,-0.581499,-1.930727,-1.271604

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(encoded, y, test_size=0.20, random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)
print("Predected value:")
print(y_pred[:10])
print("\nActual value:")
print(y_test[:10])

Predected value:
['C' 'D' 'D' 'A' 'A' 'D' 'A' 'C' 'D' 'F']

Actual value:
521    C
737    D
740    D
660    A
411    A
678    D
626    A
513    C
859    D
136    F
Name: final_grade, dtype: object

In [ ]:
joblib.dump(model,"student_performance_dataset.pkl")
joblib.dump(scaler,"scaler.pkl")
joblib.dump(encoded.columns.tolist(), "columns.pkl")
print("Model and preprocessing objects saved successfully!")

Model and preprocessing objects saved successfully!